### PR TITLE
rule-based cleaning before lang id

### PR DESCRIPTION
**Pull request by PinzhenChen**
Remove empty lines before running language ID to prevent `tools/langid-fasttext.py` from complaining about empty lines.

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
I am concerned that this might be very good for WMT but bad for non-WMT use cases.

Frequently in the wild the user might input sentences that contain some foreign language words (like original Chinese/Cyrillic spelling of names). Often, a model can learn to just copy these symbols to the target, however if the symbols are missing entirely from the vocab it, can never perform a copy.

**Comment by PinzhenChen** [comment]
I agree with XapaJIaMnu. Now the code is commented out. This can be used with some args.

**Comment by XapaJIaMnu** [comment]
Maybe you forgot to push?

**Comment by PinzhenChen** [comment]
The code to removing non-Latin is in `train-student/clean/tools/clean-parallel.py` which is commented out. 

Changes made to `train-student/clean/clean-corpus.sh` is to remove empty lines before predicting the language.

**Pull request merged**
