### PR TITLE
Fix config files

### PR DESCRIPTION
**Pull request by qianqianzhu**
This PR closes https://github.com/browsermt/students/issues/33.

I haven't removed `lex.s2t.gz` from the download scripts yet as I found some speed test scripts relied on those files. E.g.,

https://github.com/browsermt/students/blob/5b3736dfbf66219b7a5eee63b95b003f615db2d8/deen/ende.student.tiny11/speed.cpu.intgemm8bit.sh#L19

Let me know if I shall replace `lex.s2t.gz` to `lex.s2t.bin` in those speed test scripts (so `lex.s2t.gz` can be completely removed in this repo).

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
Yes! All the speed tests should also rely on the binary version. Unless @jerinphilip uses those scripts?

**Comment by jerinphilip** [comment]
As mentioned elsewhere, I'm open to changing CI scripts. Just let me know when breaking things happen in the archive downloaded.

**Comment by XapaJIaMnu** [comment]
@jerinphilip what would you prefer. 

Would a separate archive that you use for testing that is generated independently from the rest of the student models work for you? You use German correct?

**Comment by kpu** [comment]
We should fix the CI scripts.  If it wants to depend on the text format (like some of them should for integration testing) then we can do something separate as @XapaJIaMnu suggests.  But let's get this in.

**Review by XapaJIaMnu — APPROVED** [review]

**Comment by qianqianzhu** [comment]
Sorry, I forgot to remove `server.intgemm8bitalpha.yml` from the deployment script.

**Pull request merged**
