### PR TITLE
Farsi-English models 

### PR DESCRIPTION
**Pull request by sukantasen**
Added Farsi-English v1.0 student models.

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
Hey,

Could you please make sure the model is picked up automatically by the deployment script:

https://github.com/browsermt/students/blob/ef3ec8cb6dfe55be23fe957afbce02839b5e7776/deploy.students.sh#L9

Cheers,

Nick

**Comment by XapaJIaMnu** [comment]
@sukantasen  ping

**Comment by kpu** [comment]
fa-en losing too much quality from SentencePiece and knowledge distillation:
https://docs.google.com/spreadsheets/d/1DUXZf1pA5aJupXW4Y6YDt6qy69dF0VS2uQlhYWl-YT4/edit?usp=sharing

Also, the bergamot-translator stack is inflicting further harm compared to command-line browsermt/marian-dev at least when doing an end-to-end copy-paste test of 2013 in translateLocally.  I thought it was the token limit but raised this to 512 and most of the loss was still there.  

Lots to investigate here.

**Comment by jerinphilip** [comment]
> Also, the bergamot-translator stack is inflicting further harm compared to command-line browsermt/marian-dev at least when doing an end-to-end copy-paste test of 2013 in translateLocally. 

The following seems to be the results on validation set when I try to reproduce, keeping parameters comparable. 

```
browsermt/marian-dev                     BLEU: 28.9 62.8/36.5/23.5/15.5
bergamot-translator (line = sentence)    BLEU: 28.9 63.0/36.6/23.5/15.5 
bergamot-translator (ssplitter active)   BLEU: 28.9 61.7/35.8/22.9/15.0 

```

Run log from `set -x` (on var);
```
+ MARIAN=/home/jphilip/code/marian-dev/build
+ BGMT=/home/jphilip/code/bergamot-translator/build
+ mkdir -p speed_intgemm
+ COMMON_ARGS=(--relative-paths -m model.intgemm.alphas.bin -v ../vocab.faen.spm ../vocab.faen.spm --int8shiftAlphaAll --beam-size 1 --skip-cost --shortlist ../lex.s2t.bin false --cpu-threads 1 --quiet --quiet-translation --log speed_intgemm/valid.intgemm.cpu.log)

+ /home/jphilip/code/marian-dev/build/marian-decoder --mini-batch 32 --maxi-batch 100 --maxi-batch-sort src -w 128 -i ../../data/valid.fa -o speed_intgemm/output.intgemm.en --relative-paths -m model.intgemm.alphas.bin -v ../vocab.faen.spm ../vocab.faen.spm --int8shiftAlphaAll --beam-size 1 --skip-cost --shortlist ../lex.s2t.bin false --cpu-threads 1 --quiet --quiet-translation --log speed_intgemm/valid.intgemm.cpu.log

+ /home/jphilip/code/bergamot-translator/build/app/bergamot --bergamot-mode decoder --relative-paths -m model.intgemm.alphas.bin -v ../vocab.faen.spm ../vocab.faen.spm --int8shiftAlphaAll --beam-size 1 --skip-cost --shortlist ../lex.s2t.bin false --cpu-threads 1 --quiet --quiet-translation --log speed_intgemm/valid.intgemm.cpu.log --ssplit-mode sentence --mini-batch-words 1024 --max-length-break 1024

+ /home/jphilip/code/bergamot-translator/build/app/bergamot --bergamot-mode native --relative-paths -m model.intgemm.alphas.bin -v ../vocab.faen.spm ../vocab.faen.spm --int8shiftAlphaAll --beam-size 1 --skip-cost --shortlist ../lex.s2t.bin false --cpu-threads 1 --quiet --quiet-translation --log speed_intgemm/valid.intgemm.cpu.log --ssplit-mode paragraph --mini-batch-words 1024 --max-length-break 1024

+ sacrebleu -f text ../../data/valid.en
+ tee valid.bleu.intgemm


BLEU|nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.0.0 = 28.9 62.8/36.5/23.5/15.5 (BP = 0.956 ratio = 0.957 hyp_len = 21121 ref_len = 22081)
+ sacrebleu -f text ../../data/valid.en
+ tee valid.bleu.intgemm.bgmt.decoder
BLEU|nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.0.0 = 28.9 63.0/36.6/23.5/15.5 (BP = 0.953 ratio = 0.954 hyp_len = 21067 ref_len = 22081)
+ sacrebleu -f text ../../data/valid.en
+ tee valid.bleu.intgemm.bgmt.faithful
BLEU|nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.0.0 = 28.9 61.7/35.8/22.9/15.0 (BP = 0.979 ratio = 0.979 hyp_len = 21617 ref_len = 22081)
```

translateLocally might want to tune [the hardcoded parameters](https://github.com/XapaJIaMnu/translateLocally/blob/master/src/MarianInterface.cpp#L14-L20), (or make it configurable in QSettings?). SentenceSplitter's default of 128 token wrap doesn't seem to make a difference for me. So I'm not sure if this is a translateLocally issue.

**Comment by kpu** [comment]
I wonder if this is fun with Unicode and copy-paste.

**Pull request merged**
