### PR TITLE
Add CC-BY-SA 4.0 as license terms for models.

### PR DESCRIPTION
**Pull request by ugermann**
Current licensing terms address only software but not models (which admittedly, aren't in this repository, but users will want to know). Btw, CUNI has "officially" (per email to me from both Ondrej Bojar and Jan Hajic) consented to releasing the cs-en/en-ce students under CC-BY-SA, dropping the NC requirement.

@kpu @snukky @XapaJIaMnu: Everyone fine with CC-BY-SA 4.0 for Bergamot student models? Any other parties that would need to consent? I'm double-checking consent because I want to deploy these models in the ELG. Bergamot will be acknowledged in the Metadata.

### CODE REVIEW

**Comment by snukky** [comment]
Fine with me.

**Comment by XapaJIaMnu** [comment]
Fine with me as well

**Comment by XapaJIaMnu** [comment]
I'm also fine with it

**Comment by XapaJIaMnu** [comment]
@ugermann since nobody has responded I'm going to merge this.

**Pull request merged**
